language: erlang
branches:
    only:
        - master
        - release_2.0
matrix:
    include:
        - otp_release: 20.0
        - otp_release: 19.3
        - otp_release: 18.3
          env: COWBOY_VERSION=1.1.2
        - otp_release: 17.5
          env: COWBOY_VERSION=1.1.2
        - otp_release: R16B03-1
          env: COWBOY_VERSION=1.1.2
cache:
    directories:
        - $HOME/.cache/rebar3
        - priv/node_modules
install:
    - ./rebar3 deps
    - nvm install 6.2 && nvm use 6.2
    - make bootstrap_front_end
script:
    - make test
    - make test_front_end
    - if [ $TRAVIS_OTP_RELEASE = "20.0" ]; then make doc dialyzer; fi
    - if [ $TRAVIS_OTP_RELEASE = "17.5" ]; then make dialyzer; fi   # run dialyzer with cowboy 1.x too
after_success:
    - ./rebar3 cover
    - if [ $TRAVIS_OTP_RELEASE = "20.0" ]; then ./rebar3 coveralls send; fi
