language: erlang
branches:
    only:
        - master
otp_release:
    - 19.2
    - 18.3
    - 17.5
    - R16B03-1
install:
    ./rebar3 deps
script:
    make test
after_success:
    - ./rebar3 cover
    - if [ $TRAVIS_OTP_RELEASE = "18.3" ]; then ./rebar3 coveralls send; fi
