language: erlang
branches:
    only:
        - master
otp_release:
    - 19.2
    - 18.3
    - 17.5
    - R16B03-1
script:
    make test
after_success:
    - ./rebar3 cover
    - if [ $TRAVIS_OTP_RELEASE = "18.3" ]; then erl -noshell -pa _build/test/lib/*/ebin -eval 'ecoveralls:travis_ci("_build/test/cover/ct.coverdata"), init:stop()'; fi
